
const cfg=window.FENIX_CONFIG;
const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_KEY);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtMoney=n=>n==null?'':new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n));
const fmtDate=d=>d?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'';
async function getSessionUser(){const {data:{user}}=await sb.auth.getUser();return user}
async function getProfile(user){if(!user)return null;const {data,error}=await sb.from('fenix_profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;return data}
async function uploadImage(file,folder='general'){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(cfg.MEDIA_BUCKET).upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from(cfg.MEDIA_BUCKET).getPublicUrl(path).data.publicUrl}

function fenixBrand(){document.querySelectorAll('.brand').forEach(el=>{el.innerHTML='<span style="display:inline-flex;align-items:center;gap:10px"><img src="fenix-logo.jpg" alt="Transportes Fénix" style="width:44px;height:44px;object-fit:cover;border-radius:10px;border:1px solid #b58b2a"><span>TRANSPORTES FÉNIX</span></span>'})}
function moneyNum(v){const n=Number(v);return Number.isFinite(n)?n:0}
let fenixCostCache=[];
function customerExtrasTotal(){return fenixCostCache.filter(x=>x.category!=='gasto_interno').reduce((s,x)=>s+moneyNum(x.amount),0)}
function internalCostsTotal(){return fenixCostCache.filter(x=>x.category==='gasto_interno').reduce((s,x)=>s+moneyNum(x.amount),0)}
function fenixRecalc(){const u=document.getElementById('unitPrice'),d=document.getElementById('billableDays'),t=document.getElementById('quotedAmount'),h=document.getElementById('priceHelp');if(!u||!d||!t)return;const base=moneyNum(u.value),days=Math.max(1,parseInt(d.value||'1',10)||1),extras=customerExtrasTotal(),total=base*days+extras;t.value=total.toFixed(2);t.readOnly=true;if(h)h.textContent=`${fmtMoney(base)} × ${days} día(s) + ${fmtMoney(extras)} de costos adicionales = ${fmtMoney(total)}`;return total}
async function fenixLoadCosts(id){const {data,error}=await sb.from('fenix_quote_costs').select('*').eq('quote_id',id).order('created_at',{ascending:true});if(error)throw error;fenixCostCache=data||[];const cr=document.getElementById('costRows'),ir=document.getElementById('internalCostRows');if(cr)cr.innerHTML=fenixCostCache.filter(x=>x.category!=='gasto_interno').map(x=>`<div class="line"><span>${esc(x.concept||'Costo adicional')}</span><span>${fmtMoney(x.amount)} <button type="button" class="ghost" onclick="fenixRemoveCost('${x.id}')">Quitar</button></span></div>`).join('')||'<p class="muted small">Sin costos adicionales para el cliente.</p>';if(ir)ir.innerHTML=fenixCostCache.filter(x=>x.category==='gasto_interno').map(x=>`<div class="line"><span>${esc(x.concept||'Gasto interno')}</span><span>${fmtMoney(x.amount)} <button type="button" class="ghost" onclick="fenixRemoveCost('${x.id}')">Quitar</button></span></div>`).join('')||'<p class="muted small">Sin gastos internos.</p>';fenixRecalc()}
async function fenixRemoveCost(id){let qid=document.querySelector('#quoteEdit [name=id]')?.value;const {error}=await sb.from('fenix_quote_costs').delete().eq('id',id);if(error)return alert(error.message);if(qid)await fenixLoadCosts(qid)}
async function fenixAddCost(category){const qid=document.querySelector('#quoteEdit [name=id]')?.value;const concept=document.getElementById(category==='gasto_interno'?'internalCostConcept':'costConcept');const amount=document.getElementById(category==='gasto_interno'?'internalCostAmount':'costAmount');if(!qid||!concept?.value||moneyNum(amount?.value)<=0)return alert('Captura concepto e importe.');const {error}=await sb.from('fenix_quote_costs').insert({quote_id:qid,concept:concept.value.trim(),amount:moneyNum(amount.value),category});if(error)return alert(error.message);concept.value='';amount.value='';await fenixLoadCosts(qid)}
async function fenixFinance(){const m=document.getElementById('financeMonth')?.value;if(!m)return;const start=`${m}-01T00:00:00`,end=new Date(`${m}-01T00:00:00`);end.setMonth(end.getMonth()+1);const [{data:q},{data:c}]=await Promise.all([sb.from('fenix_quote_requests').select('id,quote_folio,requester_name,quoted_amount,status,created_at').gte('created_at',start).lt('created_at',end.toISOString()),sb.from('fenix_quote_costs').select('quote_id,amount,category').eq('category','gasto_interno')]);const rows=q||[],costs=c||[];const cm={};costs.forEach(x=>cm[x.quote_id]=(cm[x.quote_id]||0)+moneyNum(x.amount));const rev=rows.reduce((s,x)=>s+moneyNum(x.quoted_amount),0),co=rows.reduce((s,x)=>s+(cm[x.id]||0),0);if(window.fRevenue)fRevenue.textContent=fmtMoney(rev);if(window.fCosts)fCosts.textContent=fmtMoney(co);if(window.fMargin)fMargin.textContent=fmtMoney(rev-co);if(window.fClosed)fClosed.textContent=rows.filter(x=>x.status==='finalizada').length;if(window.financeRows)financeRows.innerHTML=rows.map(x=>`<tr><td>${esc(x.quote_folio||'')}</td><td>${esc(x.requester_name||'')}</td><td>${fmtMoney(x.quoted_amount||0)}</td><td>${fmtMoney(cm[x.id]||0)}</td><td>${fmtMoney(moneyNum(x.quoted_amount)-(cm[x.id]||0))}</td></tr>`).join('')}
function setupFenixAdmin(){if(!document.getElementById('quoteEdit'))return;const pm=document.getElementById('priceMode');if(pm){pm.value='por_dia';pm.disabled=true;pm.closest('div').style.display='none'}const ua=document.getElementById('unitPrice'),bd=document.getElementById('billableDays'),qa=document.getElementById('quotedAmount');if(qa)qa.readOnly=true;if(ua)ua.oninput=fenixRecalc;if(bd)bd.oninput=fenixRecalc;const cr=document.getElementById('costRows');if(cr){const h=cr.previousElementSibling;if(h&&h.tagName==='H3')h.textContent='Costos adicionales para el cliente';const grid=cr.nextElementSibling;if(grid){const box=document.createElement('div');box.innerHTML='<h3 style="margin-top:24px">Gastos internos del viaje</h3><p class="muted small">Solo administración. No se suman al total del cliente ni aparecen en la cotización.</p><div id="internalCostRows"></div><div class="grid3"><input id="internalCostConcept" placeholder="Concepto interno"><input id="internalCostAmount" type="number" step="0.01" placeholder="Importe"><button type="button" class="ghost" id="addInternalCost">+ Agregar gasto interno</button></div>';grid.after(box);document.getElementById('addInternalCost').onclick=()=>fenixAddCost('gasto_interno')}}const ac=document.getElementById('addCost');if(ac)ac.onclick=()=>fenixAddCost('cliente_adicional');window.loadQuoteCosts=fenixLoadCosts;window.recalcPrice=fenixRecalc;window.loadFinance=fenixFinance;window.removeCost=fenixRemoveCost;const form=document.getElementById('quoteEdit');form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const id=form.elements.id.value;if(!id)return;const total=fenixRecalc();const payload={status:form.elements.status.value,price_mode:'por_dia',unit_price:moneyNum(form.elements.unit_price.value),billable_days:Math.max(1,parseInt(form.elements.billable_days.value||'1',10)||1),quoted_amount:total,admin_notes:form.elements.admin_notes.value||null,vehicle_id:form.elements.vehicle_id.value||null};if(form.elements.bank_account_id)payload.bank_account_id=form.elements.bank_account_id.value||null;const {error}=await sb.from('fenix_quote_requests').update(payload).eq('id',id);if(error)return alert(error.message);if(typeof loadQuotes==='function')await loadQuotes();if(typeof loadAssignments==='function')await loadAssignments();await fenixFinance();alert('Cotización actualizada correctamente.');},{capture:true})}
async function renderFenixQuote(){if(!document.getElementById('sheet'))return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const [{data:q,error},{data:costs}]=await Promise.all([sb.from('fenix_quote_requests').select('*,fenix_vehicles(name,category,passenger_capacity)').eq('id',id).single(),sb.from('fenix_quote_costs').select('concept,amount,category').eq('quote_id',id)]);if(error||!q)return;const extras=(costs||[]).filter(x=>x.category!=='gasto_interno');const base=moneyNum(q.unit_price),days=Math.max(1,parseInt(q.billable_days||1,10)),extrasTotal=extras.reduce((s,x)=>s+moneyNum(x.amount),0),total=base*days+extrasTotal;const sheet=document.getElementById('sheet');sheet.innerHTML=`<div style="display:flex;justify-content:space-between;gap:24px;align-items:flex-start;border-bottom:2px solid #b58b2a;padding-bottom:18px;margin-bottom:18px"><div><img src="fenix-logo.jpg" alt="Transportes Fénix" style="width:210px;max-width:46vw;border-radius:12px"><div class="muted small" style="margin-top:8px">TU DESTINO, EN BUENAS MANOS.</div></div><div style="text-align:right"><div class="eyebrow">Cotización de servicio</div><h2 style="margin:4px 0">${esc(q.quote_folio||'')}</h2><div class="muted small">Emitida ${new Intl.DateTimeFormat('es-MX',{dateStyle:'long'}).format(new Date())}</div></div></div><div class="line"><b>Cliente</b><span>${esc(q.requester_name||'')}</span></div><div class="line"><b>Empresa</b><span>${esc(q.company_name||'—')}</span></div><div class="line"><b>Ruta</b><span>${esc(q.origin)} → ${esc(q.destination)}</span></div><div class="line"><b>Salida</b><span>${fmtDate(q.departure_at)}</span></div><div class="line"><b>Regreso</b><span>${q.return_at?fmtDate(q.return_at):'—'}</span></div><div class="line"><b>Pasajeros</b><span>${esc(q.passengers)}</span></div><div class="line"><b>Unidad propuesta</b><span>${esc(q.fenix_vehicles?.name||'Por asignar')}</span></div><h3 style="margin-top:26px">Desglose</h3><div class="line"><b>Precio base por día</b><span>${fmtMoney(base)} × ${days} día(s) = ${fmtMoney(base*days)}</span></div>${extras.map(x=>`<div class="line"><span>${esc(x.concept||'Costo adicional')}</span><span>${fmtMoney(x.amount)}</span></div>`).join('')}<div style="display:flex;justify-content:space-between;align-items:center;margin-top:20px;padding:18px;border:1px solid #b58b2a;border-radius:14px"><b>Total cotizado</b><span class="amount">${fmtMoney(total)}</span></div><p class="muted small" style="margin-top:24px">Cotización sujeta a disponibilidad y confirmación final del servicio. Los gastos internos de operación y los datos bancarios de administración no se muestran al cliente.</p>`;}
window.addEventListener('DOMContentLoaded',()=>{fenixBrand();setupFenixAdmin();if(location.pathname.endsWith('/cotizacion.html')||location.pathname.endsWith('cotizacion.html'))setTimeout(renderFenixQuote,350)});
